Test generating a report in workflow

diff --git a/.github/workflows/test_ci.yml b/.github/workflows/test_ci.yml
--- a/.github/workflows/test_ci.yml
+++ b/.github/workflows/test_ci.yml
@@ -38,63 +38,87 @@ jobs:
         run: |
           npm install -g @axe-core/cli
           CHROMEDRIVER_PATH=$(which chromedriver)
-          axe --chromedriver-path $CHROMEDRIVER_PATH $APP/${{ matrix.webpage }} --dir ./results/axe/ --save axe-results-${{ matrix.webpage }}.json
+          axe --chromedriver-path $CHROMEDRIVER_PATH $APP/${{ matrix.webpage }} --dir ./results/axe/ --save axe-results.json
       - name: Archive axe-core test results
         uses: actions/upload-artifact@v4
         with:
-          name: Axe-core
+          name: Axe-core-${{ matrix.webpage }}
           path: results/axe/axe-results.json
 
-  achecker:
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        webpage: [perceivable, operable, understandable]
-    steps:
-      - uses: actions/checkout@v4
-      - name: Use Node.js 18
-        uses: actions/setup-node@v4
-        with:
-          node-version: 18.x
-      - run: npm ci
-      - run: npm run build --if-present
-      - run: npm start & npx wait-on $APP
-      - name: Run accessibility-checker
-        run: |
-          npm install accessibility-checker
-          npx achecker $APP/${{ matrix.webpage }}
-      - name: Archive accessibility-checker test results
-        if: success() || failure()
-        uses: actions/upload-artifact@v4
-        with:
-          name: Accessibility-checker-${{ matrix.webpage }}
-          path: results/achecker/*
+  # achecker:
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     matrix:
+  #       webpage: [perceivable, operable, understandable]
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - name: Use Node.js 18
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 18.x
+  #     - run: npm ci
+  #     - run: npm run build --if-present
+  #     - run: npm start & npx wait-on $APP
+  #     - name: Run accessibility-checker
+  #       run: |
+  #         npm install accessibility-checker
+  #         npx achecker $APP/${{ matrix.webpage }}
+  #     - name: Archive accessibility-checker test results
+  #       if: success() || failure()
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: Accessibility-checker-${{ matrix.webpage }}
+  #         path: results/achecker/*
 
-  htmlcs:
+  # htmlcs:
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     matrix:
+  #       webpage: [perceivable, operable, understandable]
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - name: Use Node.js 18
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 18.x
+  #     - run: npm ci
+  #     - run: npm run build --if-present
+  #     - run: npm start & npx wait-on $APP
+  #     - name: Run HTML_CodeSniffer
+  #       run: |
+  #         npm i --save html_codesniffer
+  #         cd node_modules/html_codesniffer
+  #         npm install
+  #         cd ../..
+  #         npm i puppeteer
+  #         bash test.bash run htmlcs $APP/${{ matrix.webpage }}
+  #     - name: Archive HTML_CodeSniffer test results
+  #       if: success() || failure()
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: HTML_CodeSniffer-${{ matrix.webpage }}
+  #         path: results/HTML_CodeSniffer/*
+
+  report:
     runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        webpage: [perceivable, operable, understandable]
     steps:
       - uses: actions/checkout@v4
       - name: Use Node.js 18
         uses: actions/setup-node@v4
         with:
-          node-version: 18.x
-      - run: npm ci
-      - run: npm run build --if-present
-      - run: npm start & npx wait-on $APP
-      - name: Run HTML_CodeSniffer
+          node-version: 21.x
+      - name: Create output JSON
         run: |
-          npm i --save html_codesniffer
-          cd node_modules/html_codesniffer
-          npm install
-          cd ../..
-          npm i puppeteer
-          bash test.bash run htmlcs $APP/${{ matrix.webpage }}
-      - name: Archive HTML_CodeSniffer test results
-        if: success() || failure()
+          echo "{"summary": [], "report": []}"" > results/report.json
+      - name: Download axe results
+        uses: actions/download-artifact@v3
+        with:
+          name: Axe-core-perceivable
+      - name: Generate report
+        run: |
+          node generate_report.js axe ./Axe-core-perceivable/axe-results.json
+      - name: Archive report
         uses: actions/upload-artifact@v4
         with:
-          name: HTML_CodeSniffer-${{ matrix.webpage }}
-          path: results/HTML_CodeSniffer/*
+          name: Report
+          path: results/report.json
